version: 2

project_name: talizen

before:
  hooks:
    - go mod tidy

builds:
  - id: talizen
    main: ./cmd/talizen
    binary: talizen
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X bysir/talizen-cli/internal/cli.version={{ .Version }}

archives:
  - id: default
    ids:
      - talizen
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: talizen
    name: talizen-cli
  draft: false
  prerelease: auto
